### ISSUE TITLE
[원티드 사전과제] 왜 Repository에 아무 내용이 없나요..?

### ISSUE THREAD

**Issue by sawogus29** [pocojang/jsdoc-boilerplate#1]
[원티드 프론트엔드 챌린지 9월 사전과제](https://gist.github.com/pocojang/3c3d4470a3d2a978b5ebfb3f613e40fa) 에서 링크 타고 넘어왔습니다.

해당 과제 설명에 'JSDoc 환경구성이 어려우면 boiler-plate를 사용하라' 고 되어있는데, 
여기에는 아무것도 없네요;;

혹시 아직 내용을 안 올리신 건가요?

아니면... 구글링 해보니 [우아한 테크코스 Repository](https://github.com/woowacourse/jsdoc-boilerplate)가 나오는데,
원래는 우테코 링크를 올리시려던 걸까요?

**Comment by pocojang** [comment]
안녕하세요
@sawogus29 님

사실 별 다른 요청이 없어서 과제하시는 분들이 계시긴한건지..
정말 요청하시는 분이 있을 때까지 올리지 않고 있었습니다 😢 

요청해주셔서 바로 [코드 반영](https://github.com/pocojang/jsdoc-boilerplate/commit/6fc2ec19d1b66b2d04bef4ecf3d4c6c0bbb9efb5)했습니다

감사합니다
